// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ValidarenviomensajeTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","src/main/resources/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void validarenviomensaje() {
    // Test name: validar_envio_mensaje 
    // Step # | name | target | value
    // 1 | open | http://automationpractice.com/index.php?controller=contact | 
    driver.get("http://automationpractice.com/index.php?controller=contact");
    // 2 | setWindowSize | 1936x1056 | 
    driver.manage().window().setSize(new Dimension(1936, 1056));
    // 3 | click | css=.columns-container | 
    driver.findElement(By.cssSelector(".columns-container")).click();
    // 4 | click | id=id_contact | 
    driver.findElement(By.id("id_contact")).click();
    // 5 | select | id=id_contact | label=Servicio al Cliente
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Servicio al Cliente']")).click();
    }
    // 6 | click | id=id_contact | 
    driver.findElement(By.id("id_contact")).click();
    // 7 | click | id=email | 
    driver.findElement(By.id("email")).click();
    // 8 | type | id=email | h_alem@hotmail.com
    driver.findElement(By.id("email")).sendKeys("h_alem@hotmail.com");
    // 9 | click | css=.form-group:nth-child(6) | 
    driver.findElement(By.cssSelector(".form-group:nth-child(6)")).click();
    // 10 | click | id=id_order | 
    driver.findElement(By.id("id_order")).click();
    // 11 | click | id=message | 
    driver.findElement(By.id("message")).click();
    // 12 | click | id=message | 
    driver.findElement(By.id("message")).click();
    // 13 | type | id=message | Gracias por su buena atención.
    driver.findElement(By.id("message")).sendKeys("Gracias por su buena atención.");
    // 14 | click | css=#submitMessage font > font | 
    driver.findElement(By.cssSelector("#submitMessage font > font")).click();
    // 15 | assertText | css=.alert | Su mensaje ha sido enviado con éxito a nuestro equipo.
    assertThat(driver.findElement(By.cssSelector(".alert")).getText(), is("Su mensaje ha sido enviado con éxito a nuestro equipo."));
  }
}
